### PR TITLE
Port mouse event support from termbox-go

### PR DESCRIPTION
**Pull request by jonasp**
Suggestions and improvements welcome.

### CODE REVIEW

**Comment by nsf** [comment]
Would be nice to see a demo app. I know keyboard demo is messy, but Go version has mouse support in it. It's okay to make a separate demo for mouse.

I took a glance at the code, looks legit. But need to test it anyway. Will do so.. within 1-2 days.

**Comment by jonasp** [comment]
I fixed a small bug when which was resetting input_mouse when querying the input mode.
I also updated the keyboard demo to include the mouse input.

**Comment by nsf** [comment]
Thanks, demo is a nice addition to the port. As I said, will take a look on it soon. Most likely tomorrow.

**Comment by nsf** [comment]
Demo wasn't even compiling.. meh.. thanks anyway.

**Comment by jonasp** [comment]
Sorry, I screwed up the commit. I missed adding the variable declaration. I pushed a fix.

**Pull request merged**
