### PR TITLE
add sys/select.h to includes

### PR DESCRIPTION
**Pull request by dcat**
add sys/select.h to includes

### CODE REVIEW

**Comment by rofl0r** [comment]
your commit message describes what you're doing, but not why you're doing it. missing critical info.

**Comment by dcat** [comment]
well... because `termbox.c` uses `select()`.

**Comment by rofl0r** [comment]
it's still missing in the commit message. (hint: some ppl try to figure out what happened in a repo by reading commit messages. in your case they have the look at the code additionally to figure out why)

**Comment by dcat** [comment]
oh I see it now, I used github's web editor

**Comment by dcat** [comment]
rebased the commit message to be single-line, hopefully now you'll be able to read it

**Comment by rofl0r** [comment]
the problem is not that it wasn't single line (albeit the first line "update foo.c" was a bit too generic). it's that it's missing the rationale, still.
so a good commit message would tell a good summary what it's doing in the first line,
and then go on to explain the changes **and** the rationale for the changes in the next lines.

**Comment by dcat** [comment]
wait, you want me to explain the rationale between adding a dependency?

**Comment by rofl0r** [comment]
i don't want you to do anything, since this is not my repo. however if it was mine, i'd request a commit message explaining the "why".
for example:
```
foo.c: add missing include sys/select.h

the code uses select(), but the header defining it was not included.
this broke compilation on AIX.
```

**Comment by dcat** [comment]
well, let's hope the author isn't as autisticly pedantic as you are.

**Pull request merged**
