### PR TITLE
Move README to markdown format

### PR DESCRIPTION
**Pull request by george-b**
Per the comment in PR #100 this moves the README to a markdown format. I've also removed some extra blank lines between sections as this didn't always seem to be consistent.

### CODE REVIEW

**Comment by nsf** [comment]
Thanks.

**Comment by george-b** [comment]
Crap I only staged the move, I tried to force push an updated commit but it looks like you were too quick!

**Comment by nsf** [comment]
:D

**Comment by adsr** [comment]
Thanks

**Pull request merged**
